# Generated by Django 3.0.6 on 2020-05-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsmgmt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='access_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
