# Generated by Django 3.0.6 on 2020-05-16 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docsmgmt', '0003_auto_20200515_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='doc_dept',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='docsmgmt.UserDepartment'),
        ),
    ]
