# Generated by Django 3.0.6 on 2020-05-19 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docsmgmt', '0006_documents_doc_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documents',
            options={'verbose_name_plural': '1. Documents'},
        ),
        migrations.AddField(
            model_name='documents',
            name='upload_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='docsmgmt.UserProfile'),
        ),
    ]
