# Generated by Django 3.0.6 on 2020-05-19 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docsmgmt', '0008_remove_documents_upload_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='upload_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='docsmgmt.UserProfile'),
        ),
    ]
