# Generated by Django 3.0.6 on 2020-05-24 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docsmgmt', '0009_documents_upload_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accepted',
            options={'verbose_name_plural': '6.Accepted'},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name_plural': '5.Comments'},
        ),
        migrations.AlterModelOptions(
            name='documents',
            options={'verbose_name_plural': '1.Documents'},
        ),
        migrations.AlterModelOptions(
            name='refdocumenttype',
            options={'verbose_name_plural': '7.Docs Type'},
        ),
        migrations.AlterModelOptions(
            name='userdepartment',
            options={'verbose_name_plural': '2.User Department'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name_plural': '4.User Profile'},
        ),
        migrations.AlterModelOptions(
            name='usersection',
            options={'verbose_name_plural': '3.User Sections'},
        ),
        migrations.AddField(
            model_name='documents',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'พนักงาน'), (2, 'หัวหน้างาน')], null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'พนักงาน'), (2, 'หัวหน้างาน')], null=True),
        ),
        migrations.AlterField(
            model_name='documents',
            name='upload_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='docsmgmt.UserProfile'),
        ),
    ]
