# Generated by Django 3.0.6 on 2020-05-25 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsmgmt', '0011_auto_20200524_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'พนักงาน'), (2, 'หัวหน้างาน'), (3, 'พนักงานและหัวหน้างาน')], default=3, null=True),
        ),
    ]
