# Generated by Django 3.0.6 on 2020-05-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsmgmt', '0014_auto_20200525_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'พนักงาน'), (2, 'หัวหน้างาน/ผอ.กอง')], null=True),
        ),
    ]
